### ISSUE TITLE
mcmc-0.6.2.3 does not compile with covariance < 0.2.0.0

### ISSUE THREAD

**Issue by jkachmar** [dschrempf/mcmc#2]
https://github.com/dschrempf/covariance/commit/01c1d30ab33d52e4e8d4a9ad4ffb136a8d092048 renames `rescaleWith` to `rescaleSWith`, which means that as of https://github.com/dschrempf/mcmc/commit/5781ba2f194f42d1fd057f564d5571a1c42bfc56 `mcmc` needs its bounds updated to say `covariance >= 0.2` or similar.

**Comment by dschrempf** [comment]
That is correct. I use Nix and Haskell Stack to manage boundaries, but I can add this one manually!

Thank you for spotting this.

**Comment by dschrempf** [comment]
I released a new minor version.
